apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-basics
spec:
  selector:
    matchLabels:
      app: fastapi-basics
  template:
    metadata:
      labels:
        app: fastapi-basics
    spec:
      containers:
      - image: okteto.dev/fastapi-basics:1.0.0
        name: fastapi-basics

---

apiVersion: v1
kind: Service
metadata:
  name: fastapi-basics
spec:
  type: ClusterIP
  ports:
  - name: "fastapi-basics"
    port: 80
  selector:
    app: fastapi-basics

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-basics
  annotations:
    dev.okteto.com/generate-host: fastapi-basics
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: fastapi-basics
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
